name: Master Build Windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2

      # credit: https://github.com/appleboy/discord-action/issues/3#issuecomment-731426861
      - name: Discord notification
        #if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: https://foo.foo
        run: |
          $MESSAGE=@"
          {\"content\": \"Windows master build failed https://github.com/{{GITHUB_REPOSITORY}}/actions/runs/{{GITHUB_RUN_ID}}\"}
          "@
          echo $message
          C:\msys64\usr\bin\curl.exe -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST $env:DISCORD_WEBHOOK --data $MESSAGE
